@extends('pages.layout')
@php $pageTitle = 'Privacy Policy'; $pageSubtitle = "How we collect, use, and protect your data"; $breadcrumb = 'Legal'; @endphp

@section('page-content')
<div class="space-y-6 text-sm text-[#444] leading-relaxed">

    <p class="text-xs text-[#878787]">Last updated: 1 August 2026</p>

    @foreach([
        ['h'=>'1. Information We Collect','body'=>'We collect information you provide directly (name, phone, email, address), information generated by your use of the platform (order history, browsing, search queries), and device/technical information (IP address, browser type, cookie data) to improve your experience.'],
        ['h'=>'2. How We Use Your Information','body'=>'We use your information to: process and fulfill orders, send order updates and notifications, personalise your shopping experience, detect fraud and ensure platform security, improve our products and services, and comply with legal obligations.'],
        ['h'=>'3. Data Sharing','body'=>'We share your data with: sellers (only what is necessary to fulfill your order), logistics partners (for delivery), payment processors (to complete transactions), and analytics services (aggregated, anonymised data only). We never sell your personal data to third parties.'],
        ['h'=>'4. Cookies','body'=>'We use cookies to keep you logged in, remember your preferences, and analyse platform usage. You can disable cookies in your browser settings, but some features may not work correctly.'],
        ['h'=>'5. Data Security','body'=>'We implement industry-standard security measures including SSL encryption, access controls, and regular security audits. However, no internet transmission is 100% secure.'],
        ['h'=>'6. Data Retention','body'=>'We retain your personal data as long as your account is active or as needed to provide services. You may request deletion of your account and associated data at any time.'],
        ['h'=>'7. Your Rights','body'=>'Under applicable Indian data protection laws, you have the right to: access your personal data, correct inaccurate data, request deletion of your data, and withdraw consent at any time. Contact privacy@bazaarhub.in to exercise these rights.'],
        ['h'=>'8. Children\'s Privacy','body'=>'FIINWAY is not directed to children under 18. We do not knowingly collect personal information from minors without parental consent.'],
        ['h'=>'9. Changes to This Policy','body'=>'We may update this Privacy Policy periodically. We will notify you of significant changes via email or a prominent notice on the platform.'],
        ['h'=>'10. Contact Us','body'=>'For privacy-related queries, contact our Data Protection Officer at privacy@bazaarhub.in or write to us at FIINWAY Marketplace Pvt. Ltd., 12th Floor, Embassy TechVillage, Bengaluru – 560103.'],
    ] as $s)
    <div>
        <h2 class="text-base font-bold text-[#212121] mb-2">{{ $s['h'] }}</h2>
        <p>{{ $s['body'] }}</p>
    </div>
    @endforeach

</div>
@endsection
